// Code generated by Kitex v0.7.1. DO NOT EDIT.

package sourcenavigatorservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	sourcenavigatorservice "github.com/oneVegeDog/sourceNavigator/pkg/rpc/sourceNavigatorService"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *sourcenavigatorservice.CreateUserReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.Baseresp, err error)
	FindUserByName(ctx context.Context, req *sourcenavigatorservice.FindUserReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.FindUserResp, err error)
	CheckedUser(ctx context.Context, req *sourcenavigatorservice.CheckUserReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.CheckUserResp, err error)
	AddSource(ctx context.Context, addReq *sourcenavigatorservice.AddSourceReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.AddSourceResp, err error)
	FindSourceByName(ctx context.Context, findReq *sourcenavigatorservice.FindSourceByNameReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.FindSourceByNameResp, err error)
	GetSourcesByPage(ctx context.Context, getReq *sourcenavigatorservice.GetPageSourceReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.GetPageSourceResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSourceNavigatorServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSourceNavigatorServiceClient struct {
	*kClient
}

func (p *kSourceNavigatorServiceClient) Register(ctx context.Context, req *sourcenavigatorservice.CreateUserReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.Baseresp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kSourceNavigatorServiceClient) FindUserByName(ctx context.Context, req *sourcenavigatorservice.FindUserReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.FindUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindUserByName(ctx, req)
}

func (p *kSourceNavigatorServiceClient) CheckedUser(ctx context.Context, req *sourcenavigatorservice.CheckUserReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.CheckUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckedUser(ctx, req)
}

func (p *kSourceNavigatorServiceClient) AddSource(ctx context.Context, addReq *sourcenavigatorservice.AddSourceReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.AddSourceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddSource(ctx, addReq)
}

func (p *kSourceNavigatorServiceClient) FindSourceByName(ctx context.Context, findReq *sourcenavigatorservice.FindSourceByNameReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.FindSourceByNameResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindSourceByName(ctx, findReq)
}

func (p *kSourceNavigatorServiceClient) GetSourcesByPage(ctx context.Context, getReq *sourcenavigatorservice.GetPageSourceReq, callOptions ...callopt.Option) (r *sourcenavigatorservice.GetPageSourceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSourcesByPage(ctx, getReq)
}
