// Code generated by Kitex v0.7.1. DO NOT EDIT.
package sourcenavigatorservice

import (
	server "github.com/cloudwego/kitex/server"
	sourcenavigatorservice "github.com/oneVegeDog/sourceNavigator/pkg/rpc/sourceNavigatorService"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler sourcenavigatorservice.SourceNavigatorService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
