// Code generated by Kitex v0.7.1. DO NOT EDIT.

package sourcenavigatorservice

import (
			"context"
				client "github.com/cloudwego/kitex/client"
				kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
				sourcenavigatorservice "github.com/oneVegeDog/sourceNavigator/pkg/rpc/sourceNavigatorService"
)

func serviceInfo() *kitex.ServiceInfo {
	return sourceNavigatorServiceServiceInfo
 }

var sourceNavigatorServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "SourceNavigatorService"
	handlerType := (*sourcenavigatorservice.SourceNavigatorService)(nil)
	methods := map[string]kitex.MethodInfo{
		"register":
			kitex.NewMethodInfo(registerHandler, newSourceNavigatorServiceRegisterArgs, newSourceNavigatorServiceRegisterResult, false),
		"findUserByName":
			kitex.NewMethodInfo(findUserByNameHandler, newSourceNavigatorServiceFindUserByNameArgs, newSourceNavigatorServiceFindUserByNameResult, false),
		"checkedUser":
			kitex.NewMethodInfo(checkedUserHandler, newSourceNavigatorServiceCheckedUserArgs, newSourceNavigatorServiceCheckedUserResult, false),
		"addSource":
			kitex.NewMethodInfo(addSourceHandler, newSourceNavigatorServiceAddSourceArgs, newSourceNavigatorServiceAddSourceResult, false),
		"findSourceByName":
			kitex.NewMethodInfo(findSourceByNameHandler, newSourceNavigatorServiceFindSourceByNameArgs, newSourceNavigatorServiceFindSourceByNameResult, false),
		"getSourcesByPage":
			kitex.NewMethodInfo(getSourcesByPageHandler, newSourceNavigatorServiceGetSourcesByPageArgs, newSourceNavigatorServiceGetSourcesByPageResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":	 "sourcenavigatorservice",
		"ServiceFilePath": "idl\kitex_rpc\sourceNavigator.thrift",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName: 	 serviceName,
		HandlerType: 	 handlerType,
		Methods:     	 methods,
		PayloadCodec:  	 kitex.Thrift,
		KiteXGenVersion: "v0.7.1",
		Extra:           extra,
	}
	return svcInfo
}



func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*sourcenavigatorservice.SourceNavigatorServiceRegisterArgs)
	realResult := result.(*sourcenavigatorservice.SourceNavigatorServiceRegisterResult)
	success, err := handler.(sourcenavigatorservice.SourceNavigatorService).Register(ctx, realArg.Req)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newSourceNavigatorServiceRegisterArgs() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceRegisterArgs()
}

func newSourceNavigatorServiceRegisterResult() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceRegisterResult()
}


func findUserByNameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*sourcenavigatorservice.SourceNavigatorServiceFindUserByNameArgs)
	realResult := result.(*sourcenavigatorservice.SourceNavigatorServiceFindUserByNameResult)
	success, err := handler.(sourcenavigatorservice.SourceNavigatorService).FindUserByName(ctx, realArg.Req)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newSourceNavigatorServiceFindUserByNameArgs() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceFindUserByNameArgs()
}

func newSourceNavigatorServiceFindUserByNameResult() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceFindUserByNameResult()
}


func checkedUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*sourcenavigatorservice.SourceNavigatorServiceCheckedUserArgs)
	realResult := result.(*sourcenavigatorservice.SourceNavigatorServiceCheckedUserResult)
	success, err := handler.(sourcenavigatorservice.SourceNavigatorService).CheckedUser(ctx, realArg.Req)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newSourceNavigatorServiceCheckedUserArgs() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceCheckedUserArgs()
}

func newSourceNavigatorServiceCheckedUserResult() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceCheckedUserResult()
}


func addSourceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*sourcenavigatorservice.SourceNavigatorServiceAddSourceArgs)
	realResult := result.(*sourcenavigatorservice.SourceNavigatorServiceAddSourceResult)
	success, err := handler.(sourcenavigatorservice.SourceNavigatorService).AddSource(ctx, realArg.AddReq)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newSourceNavigatorServiceAddSourceArgs() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceAddSourceArgs()
}

func newSourceNavigatorServiceAddSourceResult() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceAddSourceResult()
}


func findSourceByNameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*sourcenavigatorservice.SourceNavigatorServiceFindSourceByNameArgs)
	realResult := result.(*sourcenavigatorservice.SourceNavigatorServiceFindSourceByNameResult)
	success, err := handler.(sourcenavigatorservice.SourceNavigatorService).FindSourceByName(ctx, realArg.FindReq)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newSourceNavigatorServiceFindSourceByNameArgs() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceFindSourceByNameArgs()
}

func newSourceNavigatorServiceFindSourceByNameResult() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceFindSourceByNameResult()
}


func getSourcesByPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*sourcenavigatorservice.SourceNavigatorServiceGetSourcesByPageArgs)
	realResult := result.(*sourcenavigatorservice.SourceNavigatorServiceGetSourcesByPageResult)
	success, err := handler.(sourcenavigatorservice.SourceNavigatorService).GetSourcesByPage(ctx, realArg.GetReq)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newSourceNavigatorServiceGetSourcesByPageArgs() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceGetSourcesByPageArgs()
}

func newSourceNavigatorServiceGetSourcesByPageResult() interface{} {
	return sourcenavigatorservice.NewSourceNavigatorServiceGetSourcesByPageResult()
}


type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}


func (p *kClient) Register(ctx context.Context , req *sourcenavigatorservice.CreateUserReq) (r *sourcenavigatorservice.Baseresp, err error) {
	var _args sourcenavigatorservice.SourceNavigatorServiceRegisterArgs
	_args.Req = req
	var _result sourcenavigatorservice.SourceNavigatorServiceRegisterResult
	if err = p.c.Call(ctx, "register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindUserByName(ctx context.Context , req *sourcenavigatorservice.FindUserReq) (r *sourcenavigatorservice.FindUserResp, err error) {
	var _args sourcenavigatorservice.SourceNavigatorServiceFindUserByNameArgs
	_args.Req = req
	var _result sourcenavigatorservice.SourceNavigatorServiceFindUserByNameResult
	if err = p.c.Call(ctx, "findUserByName", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckedUser(ctx context.Context , req *sourcenavigatorservice.CheckUserReq) (r *sourcenavigatorservice.CheckUserResp, err error) {
	var _args sourcenavigatorservice.SourceNavigatorServiceCheckedUserArgs
	_args.Req = req
	var _result sourcenavigatorservice.SourceNavigatorServiceCheckedUserResult
	if err = p.c.Call(ctx, "checkedUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddSource(ctx context.Context , addReq *sourcenavigatorservice.AddSourceReq) (r *sourcenavigatorservice.AddSourceResp, err error) {
	var _args sourcenavigatorservice.SourceNavigatorServiceAddSourceArgs
	_args.AddReq = addReq
	var _result sourcenavigatorservice.SourceNavigatorServiceAddSourceResult
	if err = p.c.Call(ctx, "addSource", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindSourceByName(ctx context.Context , findReq *sourcenavigatorservice.FindSourceByNameReq) (r *sourcenavigatorservice.FindSourceByNameResp, err error) {
	var _args sourcenavigatorservice.SourceNavigatorServiceFindSourceByNameArgs
	_args.FindReq = findReq
	var _result sourcenavigatorservice.SourceNavigatorServiceFindSourceByNameResult
	if err = p.c.Call(ctx, "findSourceByName", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSourcesByPage(ctx context.Context , getReq *sourcenavigatorservice.GetPageSourceReq) (r *sourcenavigatorservice.GetPageSourceResp, err error) {
	var _args sourcenavigatorservice.SourceNavigatorServiceGetSourcesByPageArgs
	_args.GetReq = getReq
	var _result sourcenavigatorservice.SourceNavigatorServiceGetSourcesByPageResult
	if err = p.c.Call(ctx, "getSourcesByPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

