// Code generated by Kitex v0.7.1. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	baseresp "github.com/oneVegeDog/sourceNavigator/pkg/rpc/baseresp"
	userservice "github.com/oneVegeDog/sourceNavigator/pkg/rpc/userService"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *userservice.CreateUserReq, callOptions ...callopt.Option) (r *baseresp.Baseresp, err error)
	FindUserByName(ctx context.Context, req *userservice.FindUserReq, callOptions ...callopt.Option) (r *userservice.FindUserResp, err error)
	CheckedUser(ctx context.Context, req *userservice.CheckUserReq, callOptions ...callopt.Option) (r *userservice.CheckUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *userservice.CreateUserReq, callOptions ...callopt.Option) (r *baseresp.Baseresp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) FindUserByName(ctx context.Context, req *userservice.FindUserReq, callOptions ...callopt.Option) (r *userservice.FindUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindUserByName(ctx, req)
}

func (p *kUserServiceClient) CheckedUser(ctx context.Context, req *userservice.CheckUserReq, callOptions ...callopt.Option) (r *userservice.CheckUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckedUser(ctx, req)
}
